apiVersion: apps/v1
kind: Deployment
metadata:
  name: status-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: status-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: status-app
    spec:
      containers:
      - name: status-app
        image: sergeys96/otus-microservices-2023:kuber_intro_v3
        ports:
          - name: web
            containerPort: 8000